macro(CHECK_A64SVE2 VARIABLE)
    if(NOT DEFINED HAVE_${VARIABLE})
        message(STATUS "Check whether A64 SVE2 can be used")
        configure_file(${PROJECT_SOURCE_DIR}/cmake/CheckA64SVE2.c.in ${PROJECT_BINARY_DIR}/CMakeFiles/CMakeTmp/CheckA64SVE2.c @ONLY)
        try_compile(HAVE_${VARIABLE} "${PROJECT_BINARY_DIR}"
            "${PROJECT_BINARY_DIR}/CMakeFiles/CMakeTmp/CheckA64SVE2.c")
        if(HAVE_${VARIABLE})
            message(STATUS "Check whether A64 SVE2 can be used - yes")
            set(${VARIABLE} 1 CACHE INTERNAL "Result of CHECK_A64SVE2" FORCE)
        else ()
            message(STATUS "Check whether A64 SVE2 can be used - no")
        endif()
    endif ()
endmacro(CHECK_A64SVE2)